name: LOWarpGUI
version: '${version}'
main: com.gmail.necnionch.myplugin.lowarpgui.bukkit.WarpGUIPlugin
api-version: 1.13
depend: [ LOInfoGUI, floodgate ]
authors: [ Necnion8 ]
softdepend: [ floodgate ]

commands:
  warp:
    aliases: [ wtp, warptp ]
    permission: warpgui.command.warp
  warpgui:
    permission: warpgui.command.warpgui
  warpguisetup:
    permission: warpgui.command.setup

permissions:
  warpgui.command.warp:
    default: true
  warpgui.command.warpgui:
    defualt: true
  warpgui.command.setup:
    default: op

  warpgui.access.*:  # pointId
    default: true
