name: LOWarpGUI
version: '${version}'
main: com.gmail.necnionch.myplugin.lowarpgui.bukkit.WarpGUIPlugin
api-version: 1.13
depend: [ LOInfoGUI ]
authors: [ Necnion8 ]
softdepend: [ floodgate ]

commands:
  warptp:
    aliases: [ wtp, warp ]
    permission: warpgui.command.warp
  warpgui:
    permission: warpgui.command.warpgui
  warpguisetup:
    permission: warpgui.command.setup

permissions:
  warpgui.command.warp: {}
  warpgui.command.warpgui: {}
  warpgui.command.setup: {}
  warpgui.access.*: {}  # pointId

  warpgui.user:
    default: true
    children:
      - warpgui.command.warp
      - warpgui.command.warpgui
      - warpgui.access.*

  warpgui.admin:
    default: op
    children:
      - warpgui.command.warp
      - warpgui.command.warpgui
      - warpgui.access.*
      - warpgui.command.setup
